server:
  port: 18080

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:11111/eureka/
    fetch-registry: true
    register-with-eureka: true


spring:
  application:
    name: GatewayService
  cloud:
    gateway:
      routes:
#        - id: EurekaClient
#          #uri: lb://EUREKA-CLIENT
#          uri: grayLb://EUREKA-CLIENT
#          predicates:
#            - Path=/EurekaClient/**
        - id: EurekaClient-V1
          uri: lb://EUREKA-CLIENT
          predicates:
            - Path=/EurekaClient/**
            - Weight=client,9
        - id: EurekaClient-V2
          uri: lb://EUREKA-CLIENT
          predicates:
            - Path=/EurekaClient/**
            - Weight=client,1


